source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target "SwiftChart_Example" do
  platform :ios, "8.3"
  pod "SwiftChart", :path => "../"
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if "#{target}" === "CropViewController" || "#{target}" === "JHRLottie" || "#{target}" === "lottie-ios" || "#{target}" === "SSZipArchive"
              puts " *** Config build settings for #{target} (#{config})"
              config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
              config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
            end
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
end
